[tools]
rust = { version = "1.92.0", profile = "default" }
shellcheck = "0.11.0"
hk = { version = "1.40.0", os = ["linux"] }
pkl = "0.31.1"

[tasks.test]
description = "Run tests"
run = "cargo test --release"

[tasks.build]
description = "Build binaries"
run = "cargo build --release"

[tasks.lint]
description = "Run linter and fix potential issues"
run = "hk run fix --all"
